### ISSUE TITLE
EventHub Produce from.body: "{{body}}" should be dynamic but it's not

### ISSUE THREAD

**Issue by pavel-mxsf** [kestra-io/plugin-azure#128]
### Expected Behavior

I'd like to call REST API and send result body to eventhub. Like this kafka blueprint:
[blueprint 151](https://kestra.io/blueprints/api/151-extract-data-from-a-rest-api-and-send-it-to-a-kafka-topic-using-the-kafka-producer-task).

### Actual Behaviour

It sends message to eventHub, but message body contains `{{ outputs.api.body }}` string instead of actual API response body.

### Steps To Reproduce

See attached example (secrets and URLs redacted), log task shows what I expect in eventHub message.

### Environment Information

- Kestra Version: 0.18.3
- Plugin version: 
- Operating System (OS / Docker / Kubernetes): Kubernetes
- Java Version (If not docker):

### Example flow

```yaml
tasks:
  - id: api
    type: io.kestra.plugin.core.http.Request
    method: GET
    uri: http://xxx.com/xxx

  - id: logRequestDone
    type: io.kestra.plugin.core.log.Log
    message:
      - "{{ outputs.api.body }}"

  - id: testEventhub
    type: io.kestra.plugin.azure.eventhubs.Produce
    from:
      body: "{{ outputs.api.body }}"
    namespace: xxx
    eventHubName: xxx
    connectionString: "xxx"
    bodySerializer: JSON    
    bodyContentType: application/json
    eventProperties:
      source: kestra
```

**Comment by anna-geller** [comment]
can you try wrapping it in `fromJson()`?

```yaml
id: repro
namespace: test
tasks:
  - id: api
    type: io.kestra.plugin.core.http.Request
    method: GET
    uri: https://reqres.in/api/repro

  - id: testEventhub
    type: io.kestra.plugin.azure.eventhubs.Produce
    disabled: true
    from:
      body: "{{ fromJson(outputs.api.body) }}"
    namespace: xxx
    eventHubName: xxx
    connectionString: "xxx"
    bodySerializer: JSON    
    bodyContentType: application/json
    eventProperties:
      source: kestra
```
