### ISSUE TITLE
Data factory failure

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/plugin-azure#172]
### Describe the issue

```
id: kangaroo_476938
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.azure.datafactory.CreateRun
    factoryName: aks-poc
    pipelineName: pipeline1
    resourceGroupName: poc
    subscriptionId: xxx
    tenantId: xxx
```

Errors with
```
loader constraint violation: when resolving method 'reactor.core.publisher.Mono io.kestra.core.serializers.FileSerde.writeAll(com.fasterxml.jackson.databind.ObjectMapper, java.io.Writer, reactor.core.publisher.Flux)' the class loader io.kestra.core.plugins.PluginClassLoader @35175e95 of the current class, io/kestra/plugin/azure/datafactory/CreateRun, and the class loader 'app' for the method's defining class, io/kestra/core/serializers/FileSerde, have different Class objects for the type reactor/core/publisher/Flux used in the signature (io.kestra.plugin.azure.datafactory.CreateRun is in unnamed module of loader io.kestra.core.plugins.PluginClassLoader @35175e95, parent loader 'app'; io.kestra.core.serializers.FileSerde is in unnamed module of loader 'app')
```

### Environment

- Kestra Version: 0.21.3
