### ISSUE TITLE
Bulk task properties are not dynamic

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-azure#57]
### Expected Behavior

Pebble value shoud be replaced accordingly
```
id: fraud_strategy
namespace: fraud_detection

inputs:
  - name: is_fraud
    type: BOOLEAN

  - name: name
    type: STRING

  - name: lastname
    type: STRING

  - name: address
    type: STRING

  - name: id_number
    type: INT


tasks:

      - id: insert_db
        type: io.kestra.plugin.azure.storage.table.Bulk
        endpoint: "https://kestrademo.table.core.windows.net/"
        connectionString: "XXXX"
        sasToken: XXX
        table: "table"
        from:
          - partitionKey: '{{inputs.id_number}}'
            rowKey: '{{execution.id}}'
            type: "UPSERT_REPLACE"
            properties:
              "name": '{{ inputs.name }}'
              "lastname": '{{ inputs.lastname }}'
              "address": '{{ inputs.address }}'
              "id_number": '{{ inputs.id_number }}'
 ```
 
 

### Actual Behaviour

but they are not
![image](https://github.com/kestra-io/plugin-azure/assets/46634684/9e7f24d4-ad81-4204-91b6-d5f59cb4cc69)

### Environment Information

- Kestra Version: v0.13.8
- Plugin version: 
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):
